language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
#  - nightly # currently points to 3.7-dev

addons:
  apt:
    packages:
      - xpra
      - xserver-xorg-video-dummy

before_install:
  - xpra --xvfb="Xorg +extension RANDR -config `pwd`/tests/res/dummy.xorg.conf -logfile ${HOME}/.xpra/xorg.log" start :42

env:
  - DISPLAY=":42"

install:
  - pip install flake8 numpy pillow pylint sphinx
  - pip install -e .

script:
  - py.test --showlocals --display=":42.0"
  - flake8 mss
  - pylint mss
  - if [[ $TRAVIS_PYTHON_VERSION > '2.8' ]];  cd docs && make clean html; fi

after_script:
  - xpra stop :42
  - cat ~/.xpra/*.log

matrix:
    fast_finish: true
